### ISSUE TITLE
Docs: Paperclip section link is displaying as unknown unicode symbol

### ISSUE THREAD

**Issue by gerth2** [PhotonVision/photonvision#1652] opened 2024-12-21 15:41 UTC
![image](https://github.com/user-attachments/assets/5e89b697-dcf1-4d6d-9018-7b4ae7ba1bd4)

Not 100% sure why, seems to be injected by sphinx during build?

![image](https://github.com/user-attachments/assets/a16f6e1e-f64b-4590-980a-5ac81ca7b31d)

Shows up like that in the HTML as well.

docs/source/_static/css/pv-icons.css refers to relative URL fonts/fontawesome-webfont.eot - but there's no fonts folder anymore there...

**Comment by Gold856** [comment] 2024-12-22 01:40
Duplicate of #1472

**Closed** 2024-12-22 01:50 UTC
Labels: bug
