### ISSUE TITLE
Missing alt for Camera Calibration video img source

### ISSUE THREAD

**Issue by tom131313** [PhotonVision/photonvision#536] opened 2022-10-25 21:15 UTC
Often the video stream does not appear in the [Camera Calibration frame](http://10.42.37.11:5800/#/cameras). Manually using browser Load image often makes the image appear. Unfortunatley there is no cue as to where the image should be thus making it hard to load manually. Please add the **alt="Stream1"** like the Dashboard image.

Cameras CAMERA CALIBRATION:
<img data-v-77d49cd0="" crossorigin="anonymous" src="http://10.42.37.11:1182/stream.mjpg?1666730398764" **alt=""** style="border-radius: 5px; display: block; object-fit: contain; object-position: 50% 50%; max-width: 100%; margin-left: auto; margin-right: auto; height: 100%; cursor: default;">

Dashboard PROCESSED:
<img data-v-016b9a7a="" id="" crossorigin="anonymous" src="http://10.42.37.11:1182/stream.mjpg?1666731148861" **alt="Stream1"** style="border-radius: 3px; display: block; object-fit: contain; object-position: 50% 50%; max-width: 100%; margin-left: auto; margin-right: auto; max-height: 380px; height: 100%; cursor: default;">

**Comment by gerth2** [comment] 2022-10-25 21:46
https://github.com/PhotonVision/photonvision/pull/529 and https://github.com/PhotonVision/photonvision/pull/422 may also be of interest to help address root cause

**Comment by gerth2** [comment] 2022-11-03 18:22
Tentatively closing this as I expect the websocket streaming to cover this up. Feel free to re-open if needed.

**Closed by gerth2** 2022-11-03 18:22 UTC
