### ISSUE TITLE
Client stream view occasionally lost on settings change

### ISSUE THREAD

**Issue by amquake** [PhotonVision/photonvision#595] opened 2022-11-14 01:34 UTC
The dashboard UI stream can sometimes "desync" and disappear when settings are changed(the target data is still available). In this video, changing from 2d to 3d while targets are visible causes this. About 30 seconds after the end of the video the stream returned.

https://user-images.githubusercontent.com/7953350/201556856-a26b2891-6577-4305-9af3-d7b4619e7808.mp4

@gerth2 :
> I do still get occasional issues, but actually I think it's more of a whole UI thing (namely, streams getting recreated with new port numbers, but those port numbers not getting broadcast to the front end)

This does not seem to happen when targets are not visible.

@gerth2 :
> i smell a race condition....

**Comment by mdurrani808** [comment] 2022-12-25 05:21
Potentially closed by #649

**Comment by mcm001** [comment] 2022-12-27 04:42
I can still reproduce the desync on latest master. Not sure where the root cause is

**Comment by amquake** [comment] 2023-01-07 02:14
Seems to be fixed by #706 . Would like corroboration before closing

**Closed** 2023-10-09 22:39 UTC
