### ISSUE TITLE
Robustly remember previous pipeline, resolution, etc. between system shutdowns

### ISSUE THREAD

**Issue by mdurrani808** [PhotonVision/photonvision#552] opened 2022-10-30 04:16 UTC
Based on #271 and reports on CD, pipeline and resolution could change between start up. More digging to be done

**Comment by gerth2** [comment] 2022-10-31 12:35
Tentative thoughts...

1) Crank up the priority/frequency of the save-to-disk
2) Add some form of a watchdog mechanism to check whether things are saved to disk, or at least flag when a save hasn't happened in a while?
3) Add a UI thingy which tells the user how long its been since last save. This won't actually fix anything, but just make it easier for end users to make reproducible test cases where they change settings, but _don't_ see a save occur.

**Comment by srimanachanta** [comment] 2023-12-01 04:11
@mcm001 is this resolved by SQL changes?

**Comment by clrozeboom** [comment] 2024-04-06 00:31
We've been having this problem lately. On the latest version. No matter what we change, the settings always revert to the last state just before the problem started happening. It's just a few settings and it's manageable but it's annoying. ;)

**Comment by mcm001** [comment] 2024-04-06 00:34
Do you have logs from a boot of Photon for which it happened?

**Comment by clrozeboom** [comment] 2024-04-06 10:58
I'll get some. Is there a way to easily reset the database? I'm fine with Linux commands if need be.

**Comment by mcm001** [comment] 2024-04-06 13:47
This is the most surefire way as of rn:  


```sudo service photonvision stop
sudo rm -rf /opt/photonvision/photonvision_config
sudo service photonvision start```

**Comment by 5010TigerDynasty** [comment] 2024-04-06 14:01
[photonvision-journalctl-4-5-24.txt](https://github.com/PhotonVision/photonvision/files/14893764/photonvision-journalctl-4-5-24.txt)
Here's our log file from the last 2 days. Thanks

**Comment by clrozeboom** [comment] 2024-04-06 19:04
FYI, we ended up putting in a spare server which is now working fine. Still have the old one.

**Comment by mcm001** [comment] 2024-04-06 19:43
> No matter what we change, the settings always revert to the last state just before the problem started happening.

Could you elaborate a bit more on what that means? I'm trying to figure out what I should be ctrl-f-ing for in the log you sent

**Comment by clrozeboom** [comment] 2024-04-06 23:26
Ok, for example the 'Top Camera' reverts from using 3-D to using 2-D. That's the most annoying thing that was happening because we wouldn't be able to get pose from it at the beginning of a match.

**Comment by mcm001** [comment] 2024-11-02 04:39
Believe this is OBE after sql and such - reopen if not

**Closed by mcm001** 2024-11-02 04:39 UTC
Labels: bug, help wanted
